version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agentdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - GPT_MODEL=${GPT_MODEL}
      - DATABASE_URL=postgres://postgres:password@postgres:5432/agentdb
      - REDIS_URL=redis://redis:6379

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000

volumes:
  pgdata:
